default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: kobecco_development
test:
  <<: *default
  database: kobecco_test
production:
  <<: *default
  database: kobecco_production
  username: kobecco
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
